---
id: plazma-slide-20180215
base_name: plazma-slide
tags:
- plazma-oss-slide
presentation_date:
version: 1.0.2
licenses: []
slideshare_id:
speaker_deck_id:
ustream_id:
vimeo_id:
youtube_id:
author:
  markup_language: :rd
  name: Hiroshi Hatake
  email: cosmo0920.wp@gmail.com
  rubygems_user: cosmo0920
  slideshare_user:
  speaker_deck_user:
